version: '3'
services:
  dev-d8.ateam:
    build: .
    environment:
      - PROJECT_NAME="ateam-d8-dvinci"
    ports:
      - 80:80
      - 222:22
      - 33306:3306
    volumes:
      - ./src/:/var/www/html
